import type, { Metadata } from "next";

import Header from "@/components/Header";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata: Metadata = {
  title: "Task manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // если пользователь не залогинен, то он не может попасть на /dahsboard
    <ProtectedRoute>
      <Header />
      <div className="p-6 max-w-4xl mx-auto">{children}</div>
    </ProtectedRoute>
  );
}
